views:
  - name: financial_performance
    description: "Comprehensive financial performance and profitability analysis"
    
    cubes:
      - join_path: financial_metrics
        includes:
          - metric_id
          - bank_inflow
          - bank_outflow
          - cash_balance
          - debt_ratio
          - management_cost
          - energy_cost
          - labor_cost
          - material_cost
          - leaf_revenue
          - seedling_revenue
          - fertilizer_cost
          - created_at
          
      - join_path: financial_metrics.daily_reports
        includes:
          - report_date
          - report_type
          
      - join_path: financial_metrics.daily_reports.companies
        includes:
          - company_name
          - department_type
          
      - join_path: financial_metrics.daily_reports.sales_metrics
        includes:
          - total_orders
          - payment_received
          - outstanding_receivables
          
      - join_path: financial_metrics.daily_reports.procurement_metrics
        includes:
          - total_procurement_cost
          - cost_savings
          